### ISSUE TITLE
cookieless handshake can cause traceback

### ISSUE THREAD

**Issue by bpytlik** [techpines/express.io#11]
If express has been configured with sessionConfig.store but an io handshake comes in with no session cookie, then the server will traceback with the following stack (line numbers may be slightly off because of prints I've inserted during debugging).

TypeError: Cannot call method 'indexOf' of undefined
    at Object.exports.parseSignedCookie (<pth>/express.io/node_modules/connect/lib/utils.js:209:19)
    at express.application.io.io.broadcast (<pth>/express.io/lib/index.coffee:98:37)
    at cookieParser (<pth>/express.io/node_modules/connect/lib/middleware/cookieParser.js:60:5)
    at express.application.io.io.broadcast (<pth>/express.io/lib/index.coffee:89:16)
    at Manager.<anonymous> (<my code>/server.js:271:14)
    at Manager.authorize (<pth>/express.io/node_modules/socket.io/lib/manager.js:913:31)
    at Manager.handleHandshake (<pth>/express.io/node_modules/socket.io/lib/manager.js:789:8)
    at Manager.handleRequest (<pth>/express.io/node_modules/socket.io/lib/manager.js:597:12)
    at Server.<anonymous> (<pth>/express.io/node_modules/socket.io/lib/manager.js:121:10)
    at Server.EventEmitter.emit (events.js:99:17)

I think the check that's needed is to make sure that 'rawCookie' is defined after its gotten from 'data.cookies[sessionConfig.key]' before 'connect.utils.parseSignedCookie' is called.

**Comment by bpytlik** [comment]
The above pull request should have fixed this issue.
