### ISSUE TITLE
Update to latest socket.io

### ISSUE THREAD

**Issue by IngwiePhoenix** [techpines/express.io#119]
I just found this project via npmjs and I totally love the concept of it and want to use it in my app. However, I have an issue...and that is, the outdated socket.io dependency. You require 0.9.x, but 1.3.x is the current. Is it possible to update master?

**Comment by xinyuwang** [comment]
I can't agree more. Looking forward the next change.

**Comment by IngwiePhoenix** [comment]
I had to revert my app back to separated socket.io and express since I need to use 1.3.x. But I’m totally looking forward to an updated version that will have the newer versions in!

BTW I tested what happens if I just kinda update all dependencies and try to run a demo:

```
Ingwie@Ingwies-Macbook-Pro.local ~/W/e/e/http-io $ node app

/Users/Ingwie/Work/express.io/compiled/index.js:106
    this.io.configure((function(_this) {
            ^
TypeError: Object #<Server> has no method 'configure'
    at EventEmitter.express.application.io (/Users/Ingwie/Work/express.io/compiled/index.js:106:13)
    at Object.<anonymous> (/Users/Ingwie/Work/express.io/examples/http-io/app.js:2:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by geekytime** [comment]
There was quite a bit of cleanup between 0.9.x and 1.3.x of socket.io. There's a [migration guide](http://socket.io/docs/migrating-from-0-9/), if anyone has time to submit a Pull Request to fix the breaks. It doesn't look too painful, but I just don't have time to try it out right now.

**Comment by IngwiePhoenix** [comment]
That actually seems do-able… If it is a 0.9 to 1.3 guide in particular, then I could do that because I do have a lot of time at hand - and I would really like to use this project! :) So I’ll see if I can make that happen...

**Comment by geekytime** [comment]
Since I posted that link, I have spent some time exploring the various options out there for WebSockets. Primus, which calls itself "an abstraction layer for real-time", [explains pretty well](https://github.com/primus/primus#socketio) why they stuck with socket.io 0.9.x.

> Note: Primus will never support Socket.IO 1.0. As it's just an abstraction build upon Engine.IO so it makes more sense to use Engine.IO in Primus directly. Socket.IO 0.9.x will be supported as it uses a completely different transport system.

I realize that express.io is coming from a very different angle than Primus, but it does make me wonder if the decision to stick with socket.io 0.9.x might have been based on similar arguments...

**Comment by IngwiePhoenix** [comment]
I have some time now...and due to a refactor of my project I will sit down and work this out now - because this project will very simply reduce the compecity of my code.

With refactor, I mean moving my code from being a single-process monster to becoming a multi-process thing. The structure is that there are multiple workers of multiple kinds. for isntance, my local maschine would spawn 8 front-end workers (serving files), 2 workers especially for the chat - that runs via socket.io - and more. But all of them go out on the same http port and such...so it will just be a ton easier if using this project.

So yeah, to the fork button I go!

**Comment by IngwiePhoenix** [comment]
...and then I learn this thing is coffeescripted. I am doomed :P I can see what needs to be changed thanks to the link for the migration guide BUT coding in a "new" language is gonna be a thing...

**Comment by IngwiePhoenix** [comment]
``` coffeescript
    @_router.stack.push layer
```

`Layer._router` does not exist...and now I dont know where to put this. Everything else so far works. But appearently, not being able to register the Layer is an issue...?

**Comment by IngwiePhoenix** [comment]
Okay okay, I got that down. However, I am now stuck at a pretty problem that I know how to solve in JS, at least I think so, but not in Coffee...

So, I re-wrote this layer function into a typical callback and now I want to overwrite `express.application.defaultConfiguration` to call `this.use(...)` with the correct context. But... how exactly do I get this right?

``` coffeescript
defaultConfiguration = express.application.defaultConfiguration
express.application.defaultConfiguration = ->
    defaultConfiguration.apply this
    @use eioInitialize
```

`eioInitialize` is the router that initializes `request.io`. I want to add this middleware upon initialization. Any idea how to solve this?

**Comment by IngwiePhoenix** [comment]
If someone can give me a hint to fix this, let me know please! :)

**Comment by sibartlett** [comment]
Sorry, I don't usually do shameless self-promotion - but I forked express.io a few months ago [here](https://github.com/sibartlett/express.oi). It supports the latest versions of both socket.io and express. I also rewrote it in plain JavaScript, and changed the API (documented in the readme).

**Comment by IngwiePhoenix** [comment]
I dont see why this would be shameless? :) It’s very nice to see you re-writing it in pure JS - it really helps a lot! CoffeeScript is just not my language…and I am very sure I am done trying to deal with it :)
Will check out the fork and see how well it turns out - thanks for letting us know about it!

**Comment by zbyte64** [comment]
+1
