### ISSUE TITLE
  app.io.enable('browser client gzip') causes an error

### ISSUE THREAD

**Issue by thomaswhite** [techpines/express.io#24]
Win 7, Node 0.10.5 
app.io.enable('browser client gzip') causes the following error:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: This socket is closed.
    at Socket._write (net.js:618:19)
    at doWrite (_stream_writable.js:211:10)
    at writeOrBuffer (_stream_writable.js:201:5)
    at Socket.Writable.write (_stream_writable.js:172:11)
    at Socket.write (net.js:596:40)
    at Socket.Writable.end (_stream_writable.js:325:10)
    at Socket.end (net.js:395:31)
    at Static.gzip (D:\2013\github\links.to\node_modules\socket.io\lib\static.js:207:14)
    at ready (D:\2013\github\links.to\node_modules\socket.io\lib\static.js:370:14)
    at D:\2013\github\links.to\node_modules\socket.io\lib\static.js:103:9

Process finished with exit code 8.

It is even more interesting that I checkout my code on another Win 7 and it is working fine there. Any ideas?

**Comment by johnnysnow** [comment]
Did you find a solution? I have exactly the same problem :)

**Comment by pittss** [comment]
try in win 7 (in both) from cmd run "gzip". i think in "broken" win 7 gzip will be not found. but in working win 7 gzip will found. 
Solution: 
1. you can fix socket.io https://github.com/fengmk2/socket.io/commit/8048ff489178958dc0cc76fc66fa7cfefea9b6cd
2. install gzip and put win PATH to him.
