### ISSUE TITLE
Can not emit events when routed from http request.

### ISSUE THREAD

**Issue by thomaswhite** [techpines/express.io#51]
When we redirect from a http request to a socket route using req.io.route('xxx") there is no emit method available. To me it very logical once we are in a socket route function to have access to all methods. 

Example: uploading a file via HTTP is routed to a socket route.  Then the server can start sending socket events to the client about the progress of the file processing.

Are there any plans to add emitting events when we use req.io.route ? If somebody can come up with a patch I would highly appreciate it.

**Comment by wensonsmith** [comment]
Yes ,i also have this problem .

```
TypeError: Object #<Object> has no method 'emit'
at Object.hello (/Users/wensonsmith/ProjectX/Server/app.js:44:12)
at Manager.io.route (/Users/wensonsmith/ProjectX/Server/node_modules/express.io/lib/index.coffee:65:29)
at Object.request.io.route (/Users/wensonsmith/ProjectX/Server/node_modules/express.io/lib/index.coffee:143:29)
at /Users/wensonsmith/ProjectX/Server/app.js:39:12
at callbacks (/Users/wensonsmith/ProjectX/Server/node_modules/express.io/node_modules/express/lib/router/index.js:160:37)
at param (/Users/wensonsmith/ProjectX/Server/node_modules/express.io/node_modules/express/lib/router/index.js:134:11)
at pass (/Users/wensonsmith/ProjectX/Server/node_modules/express.io/node_modules/express/lib/router/index.js:141:5)
at Router._dispatch (/Users/wensonsmith/ProjectX/Server/node_modules/express.io/node_modules/express/lib/router/index.js:169:5)
at Object.router (/Users/wensonsmith/ProjectX/Server/node_modules/express.io/node_modules/express/lib/router/index.js:32:10)
at next (/Users/wensonsmith/ProjectX/Server/node_modules/express.io/node_modules/connect/lib/proto.js:190:15)
```

req.io.respond is OK . 

Broadcast is also have some problem.It doesn't work .And i just wait for response for a long time . It return nothing~

My code is 

```
// Initial web request.
app.get('/hello', function(req, res) {
    // Forward to an io route.
    req.io.route('hello')
})

// Forward io route to another io route.
app.io.route('hello', function(req) {
    req.io.broadcast("world","world");
})
```

**Comment by nullivex** [comment]
You should be using app.io.broadcast. This follows the same paradigm as socket io I believe. You cannot broadcast from the contextual socket it must be done with the main socket IO object

So

``` js
app.io.broadcast()
```

Try that.

**Comment by wensonsmith** [comment]
> But apart from that: as far as I understand express.io, when you're forwarding an HTTP request to an io route, the io route should always send back a response with respond; otherwise, the HTTP request will stall.  

robertklep answer the `broadcast` question in stackoverflow http://stackoverflow.com/questions/20177184/express-io-can-not-emit-events-when-routed-from-http-request

Thank you all the same ！

And i still don;t known why req has no method emit ? Do you have any idea ?

**Comment by nullivex** [comment]
Because a request comes from the client emitting an event so the only thing you can really do is respond which matches the Socket.io documentation.

To emit an event back you would need to do `app.io.emit("even",data)`. Request just isnt the right context to emit or broadcast it needs to be done at the app level. Also when you broadcast you must still emit an event specifically to the requester as it ignores them which is be design but sort of a niggle.

**Comment by wensonsmith** [comment]
Get it!  You helped me a lot ~ THX  :+1 : )

**Comment by nullivex** [comment]
No problem. I went through the same logic process as you did so figured I would help.
